hotel.room.status.change.enabled=true
hotel.database.file=hotel_db.json
hotel.auto.save.enabled=true
book.auto.close.requests=true


#spring.datasource.url=jdbc:postgresql://postgres:5432/hotel_db
spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_db
spring.datasource.username=postgres
spring.datasource.password=qwerty123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:changelog/changelog-master.yaml
spring.liquibase.enabled=true
spring.mvc.format.date=dd-MM-yy

spring.mvc.contentnegotiation.favor-parameter=true
spring.mvc.contentnegotiation.parameter-name=format
spring.mvc.contentnegotiation.media-types.json=application/json
spring.mvc.contentnegotiation.media-types.xml=application/xml

#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
jwt.secret=vT2W7CBUE0JSktBHBuw7YKcnjapnh+ESj1962I4B3rG+XNPnIwOr63HgKATJqvb1VjIM/wAvXYbN2tG86tlBIw==
jwt.expiration-ms=86400000